#!/usr/bin/env python

import time
from datetime import datetime
import logging
from robopatrol.DAO.ConfigDBDao import ConfigDBDao
from robopatrol.Scheduler.RobopatrolScheduler import RobopatrolScheduler
from robopatrol.DAO.WaypointDao import WaypointDao
from robopatrol.Control.moveToPositionOnMap import MoveToPositionOnMap

import rospy

#CONFIGURATION
poll_interval_sec = 5

######################################################################################################
#CREATE YOUR FUNCTIONS FOR YOUR SCHEDULED JOB
def my_job():
    print('Tick! The time is: %s' % datetime.now())

def do_patrol():
    print('Starting patrol')
    # init move node
    moveNode = MoveToPositionOnMap()
    print('created move node')

    waypointDao = WaypointDao()
    waypoints = waypointDao.get_waypoints()
    for waypoint in waypoints:
        print('Waypoint: {0}').format(waypoint)
        # call action node to visit waypoint
        point = [waypoint['x'], waypoint['y'], 0]
        quarternion = [0, 0, 0, 1]
        success = moveNode.moveToPositionOnMap(point, quarternion)
        # if visit successful, update last_visited attribute on waypoint and save to server
        if success:
            waypoint['lastVisited'] = datetime.now()

            waypointDao.post_job(waypoint)

#SCHEDULER FUNCTION SECTION END
#######################################################################################################

######################################################################################################
#ADD YOUR JOB HERE.
job_listdict = [
    {
        "name": my_job,
        "displayName": "Sample job",
        "description": "Testjob, which tests the scheduler. (Remove as soon as this script is productive)",
        "cron": "0 0 * * * *"
    },
    {
        "name": do_patrol,
        "displayName": "Hourly Patrol",
        "description": "starts the patrol every hour",
        "cron": "0 15 * * * *"
    }
    #,
#    {
#        "name": my_function,
#        "description": "COPY ME ( I AM LE TEMPLATE)",
#        "cron": "* * * * * *"
#    }
]
# END JOB SECTION
######################################################################################################

def get_dict_job_by_name(jobs_dict, job_name):
    return next((job for job in jobs_dict if job['name'] == job_name), None)


def terminate(scheduler):
    scheduler.shutdown()


#Initializing stuff
rospy.init_node('Autonomous_RoboPatrol', anonymous=False)
logging.basicConfig()
scheduler = RobopatrolScheduler(job_listdict)
configDBDao = ConfigDBDao()
posted_jobs = configDBDao.post_jobs(scheduler.get_jobs_json())
if posted_jobs is False:
    print "Could not connect to the robopatrol server."
    exit(1)
scheduler.start()
scheduler.pause_all_jobs()

try:
    while True:
        time.sleep(poll_interval_sec)

        #Preconditions
        JData = configDBDao.get_jobs()
        if JData is None:
            scheduler.pause_all_jobs()
            continue

        #Pause job if not in configuration db. Reschedule job if interval changed.
        for job in scheduler.get_jobs():
            job_dict = get_dict_job_by_name(JData, job.name)
            job_dict_actual = get_dict_job_by_name(scheduler.get_jobs_json(), job.name)

            #Process actions
            if job_dict is None:
                job.pause()
            else:
                if job_dict_actual['cron'] != job_dict['cron'] or job.next_run_time is None:
                    print "modifying " + job_dict_actual['cron'] + " to " + job_dict['cron']
                    job_dict_actual['cron'] = job_dict['cron']
                    scheduler.reschedule_by_cron(job, job_dict['cron'])

except (KeyboardInterrupt, SystemExit):
    # Not strictly necessary if daemonic mode is enabled but should be done if possible
    terminate(scheduler)

